
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 4;
  public static final int PLUS = 16;
  public static final int RPAREN = 22;
  public static final int RETURN = 11;
  public static final int ERROR = 5;
  public static final int DEDENT = 15;
  public static final int IF = 3;
  public static final int LPAREN = 21;
  public static final int COLON = 12;
  public static final int ID = 2;
  public static final int NUM = 6;
  public static final int STRING = 8;
  public static final int FLOAT = 7;
  public static final int MULT = 18;
  public static final int EOF = 0;
  public static final int DEF = 10;
  public static final int DIV = 19;
  public static final int COMMENT = 9;
  public static final int MINUS = 17;
  public static final int NEWLINE = 13;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int INDENT = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "IF",
  "ELSE",
  "ERROR",
  "NUM",
  "FLOAT",
  "STRING",
  "COMMENT",
  "DEF",
  "RETURN",
  "COLON",
  "NEWLINE",
  "INDENT",
  "DEDENT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGN",
  "LPAREN",
  "RPAREN"
  };
}

